/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemahospitalar.views;



import java.time.format.DateTimeFormatter;
import javax.swing.table.DefaultTableModel;
import sistemahospitalar.backend.Enfermeiro;
import sistemahospitalar.backend.GrupoEnfermeiro;

/**
 *
 * @author caiod
 */
public class TelaListagemEnf extends javax.swing.JFrame {

    /**
     * Creates new form CadastroPac
     */

    public TelaListagemEnf() {
        initComponents();
        
        for (Enfermeiro enfermeiro : GrupoEnfermeiro.getGrupo()){
            adicionarATabela(enfermeiro);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonCadastrar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonDeletar = new javax.swing.JButton();
        jTextFieldBuscarId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonFiltrarNomes = new javax.swing.JButton();
        jTextFieldInserirNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEnfermeiro = new javax.swing.JTable();
        jButtonVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listagem de enfermeiros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 0, 24))); // NOI18N

        jButtonCadastrar.setText("CADASTRAR");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jButtonEditar.setText("EDITAR");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonDeletar.setText("DELETAR");
        jButtonDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletarActionPerformed(evt);
            }
        });

        jTextFieldBuscarId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuscarIdActionPerformed(evt);
            }
        });

        jLabel1.setText("ID:");

        jButtonFiltrarNomes.setText("FILTRAR NOMES");
        jButtonFiltrarNomes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFiltrarNomesActionPerformed(evt);
            }
        });

        jTableEnfermeiro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Enfermeiro", "Nome", "Data nascimento", "Rua", "Num", "Bairro", "Cidade", "Estado", "CEP", "Telefone", "Celular", "Email", "Setor", "Carga H Semanais", "Genero", "Treinado Op RX"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableEnfermeiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEnfermeiroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableEnfermeiro);

        jButtonVoltar.setText("voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldInserirNome, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonFiltrarNomes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCadastrar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldBuscarId, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEditar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDeletar)
                        .addGap(382, 382, 382)
                        .addComponent(jButtonVoltar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonFiltrarNomes)
                        .addComponent(jTextFieldInserirNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonDeletar)
                    .addComponent(jTextFieldBuscarId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonVoltar))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void adicionarATabela(Enfermeiro enfermeiro) {
        DefaultTableModel model = (DefaultTableModel) jTableEnfermeiro.getModel();
        Object[] rowData;
        rowData = new Object[]{
        enfermeiro.getIdEnfermeiro(),
        enfermeiro.getNomeCompleto(),
        enfermeiro.getDataNascimento().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")),
        enfermeiro.getEndereco().getRua(),
        enfermeiro.getEndereco().getNumero(),
        enfermeiro.getEndereco().getBairro(),
        enfermeiro.getEndereco().getCidade(),
        enfermeiro.getEndereco().getEstado(),
        enfermeiro.getEndereco().getCep(),
        enfermeiro.getContato().getTelefone(),
        enfermeiro.getContato().getCelular(),
        enfermeiro.getContato().getEmail(),
        enfermeiro.getSetor(),
        enfermeiro.getChSemanais(),
        enfermeiro.getGenero().getDescricao(),
        enfermeiro.isTreinadoOpRx(),
        };
        model.addRow(rowData);  
    }
    
    private void jTextFieldBuscarIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscarIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBuscarIdActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        int id = Integer.parseInt(jTextFieldBuscarId.getText());
        // Cria uma instância da Enfermeiro
        
        Enfermeiro enfermEditar = GrupoEnfermeiro.getGrupo().get(id);
        EditarEnfermeiro editEnfer = new EditarEnfermeiro(enfermEditar);

        // Torna  visível
        editEnfer.setVisible(true);

        // Opcional: fecha a TelaPrincipal se desejado
        dispose();
        
    }//GEN-LAST:event_jButtonEditarActionPerformed
    private void exibirApenasLinhaComNome(String nome) {
        DefaultTableModel model = (DefaultTableModel) jTableEnfermeiro.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            String nomeLinha = (String) model.getValueAt(i, 1); // 1 é o índice da coluna que contém o nome do enfermeiro
            if (!nomeLinha.contains(nome)) {
                // Remove a linha que não corresponde o nome pesquisado
                model.removeRow(i);
                i--; // Atualiza o índice após a remoção da linha
            }
        }
    }
    private void exibirTodasAsLinhas() {
        DefaultTableModel model = (DefaultTableModel) jTableEnfermeiro.getModel();
        model.setRowCount(0); // remove os elementos filtrados para evitar duplicação 
        
        for (Enfermeiro enfermeiro : GrupoEnfermeiro.getGrupo()){
            adicionarATabela(enfermeiro); // preenche novamente a tabela com os todos os valores 
        }
    }
    private void jButtonFiltrarNomesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFiltrarNomesActionPerformed
        // Obtem o ID do paciente digitado
        String nome = jTextFieldInserirNome.getText();
        exibirTodasAsLinhas();
        // Exibe apenas a linha que corresponde ao nome pesquisado
        if (nome.length() > 1){
            exibirApenasLinhaComNome(nome);
        }
        else {
            exibirTodasAsLinhas();
        }
    }//GEN-LAST:event_jButtonFiltrarNomesActionPerformed

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        // Cria uma instância da Enfermeiro
        CadastroEnfermeiro cadastroEnf = new CadastroEnfermeiro();

        // Torna visível
        cadastroEnf.setVisible(true);

        // Opcional: fecha a TelaPrincipal se desejado
        dispose();
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jButtonDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletarActionPerformed
        int id = Integer.parseInt(jTextFieldBuscarId.getText());
        
        GrupoEnfermeiro.removerDoGrupo(id);
        for (int i = 0; i < GrupoEnfermeiro.getGrupo().size(); i++){
            GrupoEnfermeiro.getGrupo().get(i).setIdEnfermeiro(i);
        }
        DefaultTableModel model = (DefaultTableModel) jTableEnfermeiro.getModel();
        model.setRowCount(0);
        for (Enfermeiro enfermeiro : GrupoEnfermeiro.getGrupo()){
            adicionarATabela(enfermeiro);
        }
        
    }//GEN-LAST:event_jButtonDeletarActionPerformed

    private void jTableEnfermeiroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEnfermeiroMouseClicked
        
    }//GEN-LAST:event_jTableEnfermeiroMouseClicked

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
         // Cria uma instância da TelaPaciente
        TelaPrincipal home = new TelaPrincipal();

        // Torna a TelaPaciente visível
        home.setVisible(true);

        // Opcional: fecha a TelaPrincipal se desejado
        dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaListagemEnf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaListagemEnf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaListagemEnf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaListagemEnf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaListagemEnf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonDeletar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonFiltrarNomes;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEnfermeiro;
    private javax.swing.JTextField jTextFieldBuscarId;
    private javax.swing.JTextField jTextFieldInserirNome;
    // End of variables declaration//GEN-END:variables
}
