/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemahospitalar.views;


import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.table.DefaultTableModel;
import sistemahospitalar.backend.GrupoPaciente;
import sistemahospitalar.backend.Paciente;

/**
 *
 * @author caiod
 */
public class TelaListagemPac extends javax.swing.JFrame {

    /**
     * Creates new form CadastroPac
     */

    public TelaListagemPac() {
        initComponents();
        
        for (Paciente paciente : GrupoPaciente.getGrupo()){
            adicionarPacienteATabela(paciente);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonCadastrar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonDeletar = new javax.swing.JButton();
        jTextFieldBuscarId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonFiltrarNomes = new javax.swing.JButton();
        jTextFieldInserirNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePaciente = new javax.swing.JTable();
        jButtonVoltar = new javax.swing.JButton();
        jButtonFicha = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listagem de pacientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 0, 24))); // NOI18N

        jButtonCadastrar.setText("CADASTRAR");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jButtonEditar.setText("EDITAR");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonDeletar.setText("DELETAR");
        jButtonDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletarActionPerformed(evt);
            }
        });

        jTextFieldBuscarId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuscarIdActionPerformed(evt);
            }
        });

        jLabel1.setText("ID:");

        jButtonFiltrarNomes.setText("FILTRAR NOMES");
        jButtonFiltrarNomes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFiltrarNomesActionPerformed(evt);
            }
        });

        jTablePaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID ", "Nome", "Data nascimento", "Rua", "Num", "Bairro", "Cidade", "Estado", "CEP", "Telefone", "Celular", "Email", "Data Cadastro", "Idade", "Obs Geral", "Genero"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePacienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePaciente);

        jButtonVoltar.setText("voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jButtonFicha.setText("HISTÓRICO");
        jButtonFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFichaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldBuscarId, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonFicha)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonDeletar)
                        .addGap(380, 380, 380)
                        .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldInserirNome, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonFiltrarNomes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCadastrar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonFiltrarNomes)
                        .addComponent(jTextFieldInserirNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonDeletar)
                    .addComponent(jTextFieldBuscarId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFicha))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void adicionarPacienteATabela(Paciente paciente) {
        DefaultTableModel model = (DefaultTableModel) jTablePaciente.getModel();
        Object[] rowData = new Object[]{
            paciente.getIdPaciente(),
            paciente.getNomeCompleto(),
            paciente.getDataNascimento().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")), // Formata a data antes de adicionar à tabela
            paciente.getEndereco().getRua(),
            paciente.getEndereco().getNumero(),
            paciente.getEndereco().getBairro(),
            paciente.getEndereco().getCidade(),
            paciente.getEndereco().getEstado(),
            paciente.getEndereco().getCep(),
            paciente.getContato().getTelefone(),
            paciente.getContato().getCelular(),
            paciente.getContato().getEmail(),
            paciente.getDataCadastro(),
            paciente.getIdade(),
            paciente.getObsGeral(),
            paciente.getGenero().getDescricao() 
        };
        model.addRow(rowData);   
    }
    
    private void jTextFieldBuscarIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscarIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBuscarIdActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        int idPaciente = Integer.parseInt(jTextFieldBuscarId.getText());
        
        Paciente pacienteEditar = GrupoPaciente.getGrupo().get(idPaciente);
        EditarPaciente editarPaciente = new EditarPaciente(pacienteEditar);

        // Torna a TelaPaciente visível
        editarPaciente.setVisible(true);

        // Opcional: fecha a TelaPrincipal se desejado
        dispose();
        
    }//GEN-LAST:event_jButtonEditarActionPerformed
    private void exibirApenasLinhaComNome(String nomePaciente) {
        DefaultTableModel model = (DefaultTableModel) jTablePaciente.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            String nomeLinha = (String) model.getValueAt(i, 1); // 1 é o índice da coluna que contém o nome do paciente
            if (!nomeLinha.contains(nomePaciente)) {
                // Remove a linha que não corresponde o nome do paciente pesquisado
                model.removeRow(i);
                i--; // Atualiza o índice após a remoção da linha
            }
        }
    }
    private void exibirTodasAsLinhas() {
        DefaultTableModel model = (DefaultTableModel) jTablePaciente.getModel();
        model.setRowCount(0); // remove os elementos filtrados para evitar duplicação 
        
        for (Paciente paciente : GrupoPaciente.getGrupo()){
            adicionarPacienteATabela(paciente); // preenche novamente a tabela com os todos os valores 
        }
    }
    private void jButtonFiltrarNomesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFiltrarNomesActionPerformed
        // Obtem o ID do paciente digitado
        String nomePaciente = jTextFieldInserirNome.getText();
        exibirTodasAsLinhas();
        // Exibe apenas a linha que corresponde ao nome pesquisado
        System.out.println(nomePaciente);
        if (nomePaciente.length() > 1){
            exibirApenasLinhaComNome(nomePaciente);
        }
        else {
            exibirTodasAsLinhas();
        }
    }//GEN-LAST:event_jButtonFiltrarNomesActionPerformed

    private void jTablePacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePacienteMouseClicked
       
    }//GEN-LAST:event_jTablePacienteMouseClicked

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        // Cria uma instância da TelaPaciente
        var pac = new Paciente(null, LocalDate.now(), null, null, null, null, null);
        CadastroPaciente cadastroPaciente = new CadastroPaciente(pac);

        // Torna a Tela visível
        cadastroPaciente.setVisible(true);

        // Opcional: fecha a TelaPrincipal se desejado
        dispose();
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jButtonDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletarActionPerformed
        int idPaciente = Integer.parseInt(jTextFieldBuscarId.getText());
        
        GrupoPaciente.removerDoGrupo(idPaciente);
        for (int i = 0; i < GrupoPaciente.getGrupo().size(); i++){
            GrupoPaciente.getGrupo().get(i).setIdPaciente(i);
        }
        DefaultTableModel model = (DefaultTableModel) jTablePaciente.getModel();
        model.setRowCount(0);
        for (Paciente paciente : GrupoPaciente.getGrupo()){
            adicionarPacienteATabela(paciente);
        }
        
    }//GEN-LAST:event_jButtonDeletarActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // Cria uma instância da TelaPaciente
        TelaPrincipal home = new TelaPrincipal();

        // Torna a TelaPaciente visível
        home.setVisible(true);

        // Opcional: fecha a TelaPrincipal se desejado
        dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFichaActionPerformed
        int idPaciente = Integer.parseInt(jTextFieldBuscarId.getText());
      
        Paciente pacienteFicha = GrupoPaciente.getGrupo().get(idPaciente);
    
        FichaPac fichaPac = new FichaPac(pacienteFicha);

        fichaPac.setVisible(true);

        // Opcional: fecha a TelaPrincipal se desejado
        dispose();
    }//GEN-LAST:event_jButtonFichaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaListagemPac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaListagemPac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaListagemPac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaListagemPac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaListagemPac().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonDeletar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonFicha;
    private javax.swing.JButton jButtonFiltrarNomes;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePaciente;
    private javax.swing.JTextField jTextFieldBuscarId;
    private javax.swing.JTextField jTextFieldInserirNome;
    // End of variables declaration//GEN-END:variables
}
